config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :reminders


  root to: "reminders#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reminder.rb
class Reminder < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reminders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  # GET /reminders
  # GET /reminders.json
  def index
    @reminders = Reminder.all
  end

  # GET /reminders/1
  # GET /reminders/1.json
  def show
    @reminder = Reminder.find(params[:id])
  end

  # GET /reminders/new
  def new
    @reminder = Reminder.new
  end

  # GET /reminders/1/edit
  def edit
  end

  # POST /reminders
  # POST /reminders.json
  def create
    # Process fields from the form to create a date
    reminder_date = helpers.format_date( reminder_params )

    # Build new params
    new_params = {
      :title => reminder_params[:title],
      :description => reminder_params[:description],
      :month_selection => reminder_params[:month_selection],
      :day_selection => reminder_params[:day_selection],
      :hour_selection => reminder_params[:hour_selection],
      :minute_selection => reminder_params[:minute_selection],
      :date => reminder_date
    }

    @reminder = current_user.reminders.new(new_params)

    respond_to do |format|
      if @reminder.save
        format.html { redirect_to @reminder, notice: 'Reminder was successfully created.' }
        format.json { render :show, status: :created, location: @reminder }
      else
        format.html { render :new }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reminders/1
  # PATCH/PUT /reminders/1.json
  def update
    respond_to do |format|
      if @reminder.update(reminder_params)
        format.html { redirect_to @reminder, notice: 'Reminder was successfully updated.' }
        format.json { render :show, status: :ok, location: @reminder }
      else
        format.html { render :edit }
        format.json { render json: @reminder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reminders/1
  # DELETE /reminders/1.json
  def destroy
    @reminder.destroy
    respond_to do |format|
      format.html { redirect_to reminders_url, notice: 'Reminder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reminder_params
      params.fetch(:reminder, {}).permit(:title, :description, :month_selection, :day_selection, :hour_selection, :minute_selection)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
    include ActiveSupport

    def options_for_days
        ( 1..31 ).map { |day| [ day ] }
    end

    def options_for_hours
        ( 0..23 ).map { |hour| [ format( '%02d', hour ) ] }
    end

    def options_for_minutes
        ( 0..59 ).map { |min| [ format( '%02d', min ) ] }
    end

    def options_for_months
        [[ 'Day of the month', 'day_of_month'], ['Last day of the month', 'last_day_of_month']]
    end


    def format_date( params )
        # Set Reminder timezone
        timezone = "UTC"

        days_in_month = Time::COMMON_YEAR_DAYS_IN_MONTH

        current_year = DateTime.current.year
        current_month = DateTime.current.month
        current_day = DateTime.current.day
        current_hour = DateTime.current.hour
        current_minute = DateTime.current.minute

        reminder_day = params[ :day_selection ].to_i
        reminder_hour = params[ :hour_selection ].to_i
        reminder_minute = params[ :minute_selection ].to_i

        beginning_of_month = params[ :month_selection ] == 'day_of_month'
        end_of_month = params[ :month_selection ] == 'last_day_of_month'


        if beginning_of_month #Start counting from the beginning of the month

            if reminder_day <= days_in_month[ current_month ] #Reminder day should not exceed the number of days in the current month

                if reminder_minute > current_minute + 10 || reminder_hour > current_hour || reminder_day > current_day #Set Reminder for this month (At least a 10 minute headstart for the job to run)
                    reminder_datetime = DateTime.new( current_year, current_month, reminder_day, reminder_hour, reminder_minute, 00, timezone )
                else #Set Reminder for next month
                    reminder_datetime = DateTime.new( current_year, current_month, reminder_day, reminder_hour, reminder_minute, 00, timezone ).next_month
                end

            else #Reminder day exceeds the number of days in the current month, set last day of the month
                reminder_datetime = DateTime.new( current_year, current_month, days_in_month[ current_month ], reminder_hour, reminder_minute, 00, timezone ) #Fallback to last day
            end

        else #Start counting from the end of the month

            if reminder_day <= days_in_month[ current_month ] #Reminder day should not exceed the number of days in the current month

                reverse_day = reminder_day * -1
                remaining_month_days = days_in_month[ current_month ] - current_day + 1 #Including the current day

                if reminder_minute > current_minute + 10 || reminder_hour > current_hour || reminder_day <= remaining_month_days #Set Reminder for this month (At least a 10 minute headstart for the job to run)
                    reminder_datetime = DateTime.new( current_year, current_month, reverse_day, reminder_hour, reminder_minute, 00, timezone )
                else #Set Reminder for next month
                    reminder_datetime = DateTime.new( current_year, current_month, reverse_day, reminder_hour, reminder_minute, 00, timezone ).next_month
                end

            else #Reminder day exceeds the number of days in the current month, set last day of the month
                max_reverse_day = days_in_month[ current_month ] * -1

                reminder_datetime = DateTime.new( current_year, current_month, max_reverse_day, reminder_hour, reminder_minute, 00, timezone, timezone ) # Fallback to last reverse day
            end

        end

    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReminderApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit-icons.min.js"></script>
  </head>

  <body class="uk-container">
    <div class="uk-flex uk-flex-row uk-flex-middle uk-flex-center uk-height-viewport uk-flex-wrap">
      <%= yield %>
    </div>
  </body>
</html>

app/views/reminders/_form.html.erb
<%= form_with(model: reminder, local: true) do |f| %>
  <% if reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
        <% reminder.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div uk-grid>
    <div class="uk-margin-top">
      <div>
        <%= f.label :title %><br />
        <%= f.text_field :title, class: "uk-input uk-margin-small-top" %>
      </div>

      <div class="uk-margin-top">
        <%= f.label :description %><br />
        <%= f.text_area :description, class: "uk-textarea uk-margin-small-top" %>
      </div>
    </div>

    <div class="uk-margin-top">
      <div>
        <%= f.label :day_selection %><br />
        <%= f.select :day_selection, options_for_days, { :prompt => 'Select day' }, class: "uk-select uk-margin-small-top" %>
      </div>

      <div class="uk-margin-top">
        <%= f.label :hour_selection %><br />
        <%= f.select :hour_selection, options_for_hours, { :prompt => 'Select hour' }, class: "uk-select uk-margin-small-top" %>
      </div>


    </div>

    <div class="uk-margin-top">
      <div>
        <%= f.label :month_selection %><div class="uk-margin-small-left" uk-icon="info" uk-tooltip="title: Day of the month option starts counting from the beginning of the month<br><br>Last day of the month option starts counting from the end of the month backwards"></div><br />
        <%= f.select :month_selection, options_for_months, { :prompt => 'Select month' }, class: "uk-select uk-margin-small-top" %>
      </div>

      <div class="uk-margin-top">
        <%= f.label :minute_selection %><div class="uk-margin-small-left" uk-icon="info" uk-tooltip="title: The shortest reminder you can set is 10 minutes from now<br><br>NOTICE: Timezone is UTC"></div><br />
        <%= f.select :minute_selection, options_for_minutes, { :prompt => 'Select minute' }, class: "uk-select uk-margin-small-top" %>
      </div>
    </div>


  </div>


  <div class="actions uk-margin-top uk-text-center">
    <%= f.submit 'Submit', class: "uk-button uk-button-primary" %>
    <%= link_to 'Back', reminders_path, :class => "uk-button uk-button-default" %>
  </div>

<% end %>

app/views/reminders/edit.html.erb
<div class="uk-flex uk-flex-column">
    <h1>Editing Reminder</h1>

    <%= render 'form', reminder: @reminder %>

</div>

app/views/reminders/index.html.erb
<p id="notice"><%= notice %></p>



<table class="uk-table uk-table-divider uk-table-hover uk-table-middle">
  <caption>Your reminders</caption>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.title %></td>
        <td><%= reminder.date %></td>
        <td><%= reminder.description %></td>

        <td>
          <%= link_to ' ', edit_reminder_path(reminder), {'uk-icon' => 'icon: pencil', 'alt' => 'Edit'} %>
          <%= link_to ' ', reminder, method: :delete, data: { confirm: 'Are you sure?' }, 'uk-icon' => 'icon: trash' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path, class: "uk-button uk-button-primary" %>

app/views/reminders/new.html.erb
<div class="uk-flex uk-flex-column">
    <h1>New Reminder</h1>

    <%= render 'form', reminder: @reminder %>
</div>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reminder_path(@reminder), class: 'uk-button uk-button-primary uk-display-inline-block uk-margin-small-right' %>
<%= link_to 'Back', reminders_path, class: 'uk-button uk-button-default uk-display-inline-block uk-display-inline-block ' %>